### PR TITLE
Error code

### LINKED ISSUE #14: Error code
### Description
Instead of passing errors around by wrapping each function in a `try/catch`, it would be better to pass around error codes. This repo's [code style](../blob/master/.github/CONTRIBUTING.md) reserves the right to throw exceptions if needed, but it would be good to minimize or even eliminate the amount of exceptions thrown. Reasons for this can be read [here](https://google.github.io/styleguide/cppguide.html#Exceptions).

### Possible Solution
Implement an `Ec` class as a derivative of `std::string`, whose constructors automatically format the error code appropriately.
##### Deliverables
* Class `Ec`:
  * Ec::Ec(string)
  * Ec::Ec(string, Ec)
  * Ec::Ec(string, {string, Ec})
  * Ec::Ec(string, {string, Ec}[])

### Additional Context
* Definition should go in `iex.h` header, since it will be passed to clients using the library.

### PR DESCRIPTION
**Pull request by aokellermann**
### Changes
* Implements `ec`.
* Defines generic `named_pair<T>`, which may be used again somewhere down the road.
* Closes #14.

### CODE REVIEW

File: iex/iex.h [hunk 1]
```diff
@@ -17,21 +17,72 @@
...
+#include <initializer_list>
 #include <string>
+#include <utility>
 
 namespace iex
 {
+// region named pair
+
+template <typename T>
+using named_pair = std::pair<std::string, T>;
```
Comment (aokellermann) [inline iex/iex.h:29]: Use upper camel for type names.

File: iex/iex.h [hunk 2]
```diff
@@ -17,21 +17,72 @@
...
+
+// endregion named pair
+
+// region error code
+
 /**
  * This class represents an error code.
  */
-class ec : std::string
+class ec : public std::string
```
Comment (aokellermann) [inline iex/iex.h:38]: Use upper camel for type names.
